---
title: "Semanário Leg.go"
output:
  html_document:
    css: style.css
params:
  date_init: 2019-09-30
  date_end: 2019-10-04
  num_semanas_passadas: 3
  proposicoes: !r tibble::tibble() 
  temp_pressao_periodo: !r tibble::tibble()
  atores: !r tibble::tibble()
  eventos: !r tibble::tibble()
---

```{r knitr_init, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, paged.print=FALSE, results="asis"}
library(magrittr)
knitr::opts_chunk$set(echo = FALSE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
```

```{r ,results='asis'}
library(tidyverse)
library(here)
library(lubridate)
library(ggplot2)
library(plotly)
library(hrbrthemes)
library(grid)
library(gridExtra)
library(tibble)
library(ggchicklet)
library(DT)
library(knitr)
```

<style>
body {
text-align: justify}
</style>

```{r, message=FALSE, warning=FALSE, include=FALSE}
#Base de dados de temperatura
temp_pressao_periodo <- params$temp_pressao_periodo 
data_inicio <- params$date_init
data_fim <- params$date_end
pls <- params$proposicoes
atores <- params$atores
eventos <- params$eventos
num_semanas_passadas <- params$num_semanas_passadas
```

```{r}
#Funções

define_date_breaks <- function(timedata_df) {
  time_diff <- lubridate::interval( head(timedata_df, 1)$periodo, tail(timedata_df, 1)$periodo) / days()
  time_breaks <- as.integer(abs(time_diff/5))
  datas <- seq(ymd(head(timedata_df, 1)$periodo),ymd(tail(timedata_df, 1)$periodo), by = paste(time_breaks,"days"))  
}

get_texto_temp_pressao <- function(temp_pressao_periodo, eventos_pl) {
  est_prev <- tail(temp_pressao_periodo, 2)
  temp_atual <- est_prev %>% tail(1) %>% purrr::pluck('temperatura')
  ultima_temp <- est_prev %>% head(1) %>% purrr::pluck('temperatura')
  variacao_temp <- round(((temp_atual - ultima_temp) / ultima_temp) * 100, digits = 2)
  press_atual <- est_prev$pressao[length(est_prev$pressao)]
  ultima_press <- est_prev$pressao[length(est_prev$pressao) - 1]
  variacao_press <- press_atual - ultima_press
  cresceu_temp <- variacao_temp > 1
  cresceu_press <- variacao_press > 1
  variacao_temp <- round(abs(variacao_temp),0)
  variacao_press <- round(abs(variacao_press),0)
  
  return (paste0("Foi observad", if(cresceu_temp){"o um crescimento de "}else{"a uma diminuição de "}, variacao_temp, "% na temperatura e ", if(cresceu_press){"um crescimento de "}else{ if(variacao_press == 0){"não foi observada nenhuma mudança"}else{"uma diminuição de "}}, if(variacao_press != 0){variacao_press}, if(variacao_press != 0){"%"}, " na pressão.", if(nrow(eventos_pl) > 0){" Os eventos que influenciaram a Temperatura estão na tabela abaixo."}))
}

build_temp_pressao_plot <- function(temp_pressao_pl, apelido_pl, dt_inicio, dt_fim, eventos) {
  datas <- define_date_breaks(temp_pressao_pl)
  data_n_semanas_atras <- as.Date(dt_fim) - (7 * num_semanas_passadas)
  temp_pressao_pl_n_semanas <- temp_pressao_pl %>% filter(periodo >= data_n_semanas_atras)
  
  p <- temp_pressao_pl %>% 
    ggplot(aes(x = periodo, y = sqrt(temperatura))) +
    geom_line(color="#DDDDDD") +
    geom_point(color=factor(ifelse(temp_pressao_pl$periodo==dt_inicio,"#EF476F","#DDDDDD")),
             size = ifelse(temp_pressao_pl$periodo==dt_inicio,3,1)) +
    geom_col(aes(x = periodo, y = -sqrt(pressao), width = 4), fill=factor(ifelse(temp_pressao_pl$periodo==dt_inicio,"#FFD166","#DDDDDD")), show.legend = FALSE ) +
    geom_line(data =  temp_pressao_pl_n_semanas, aes(x = periodo, y = sqrt(temperatura)), color="#EF476F") +
  geom_col(data =  temp_pressao_pl_n_semanas, aes(x = periodo, y = -sqrt(pressao), width = 4), fill=factor("#FFD166"), show.legend = FALSE ) +
    labs(x = "Semana", 
         y = "",
         title = apelido_pl) +
    scale_x_date(date_labels = "%d de %b", breaks = datas) +
    theme_ipsum_rc(grid = FALSE) +
    theme(axis.text.y = element_blank(), 
          axis.text.x = element_text(angle = 0, vjust = 0.5)) +
    theme(axis.text.x = element_text(color = "gray60", size = 8))
  
  grob <- grobTree(textGrob("Temperatura", x=0.1,  y=0.95, hjust=0,
    gp=gpar(col="black", fontsize=15, alpha = 0.3, fontfamily = "Roboto", fontface = "bold")))
  
  grob2 <- grobTree(textGrob("Pressão", x=0.1,  y=.15, hjust=0,
    gp=gpar(col="black", fontsize=15, alpha = 0.3, fontfamily = "Roboto", fontface = "bold")))
  
  temp_pressao_plot <- (p  + annotation_custom(grob) + annotation_custom(grob2))
  
  eventos_pl <- eventos %>% 
    filter(id_leggo %in% temp_pressao_pl$id_leggo) %>% 
    select("Data-Hora" = data, 
           Local = sigla_local, 
           Evento = titulo_evento,
           Detalhamento = texto_tramitacao)
  
  texto_temp_pressao <- get_texto_temp_pressao(temp_pressao_pl, eventos_pl)
  
  plot(temp_pressao_plot)
  cat(texto_temp_pressao)
  cat("\n\n")
  if (nrow(eventos_pl) == 0) {
    cat("Os eventos que fizeram a temperatura subir ainda não são reconhecidos pelo Leggo ou não são importantes.")    
  } else {
    cat("\n\n")
    cat("#### ")
    print(knitr::kable(eventos_pl))
  }
  cat("\n\n")
}

get_texto_atores_plot_bancadas_por_temas <- function(qtd_tema, atuacao_temas, atores, tema_destaque) {
  total_docs <- sum(qtd_tema$total)
  total_tema_destaque <- qtd_tema %>% filter(tema == tema_destaque) %>% purrr::pluck("total")
  variacao_temp <- round(((total_tema_destaque * 100) / total_docs), digits = 2)
  atuacao_temas_destaque <- atuacao_temas %>% filter(tema == tema_destaque)
  num_docs_governo <- atuacao_temas_destaque %>% filter(bancada == "Governo") %>% purrr::pluck("peso_total_documentos")
  num_docs_oposicao <- atuacao_temas_destaque %>% filter(bancada == "Oposição") %>% purrr::pluck("peso_total_documentos")
  
    return (paste0("Na última semana o tema ", tema_destaque, " teve destaque na atuação dos parlamentares, sendo ", variacao_temp, "% dos documentos autorados para esse tema. Outro destaque é que foram apresentados ", num_docs_governo, " documentos pela bancada do governo e ", num_docs_oposicao, " pela oposição."))
}

build_atores_plot_bancadas_por_temas <- function(atuacao_temas) {
  p <- atuacao_temas %>% ggplot(aes(x = reorder(tema,peso_total_documentos), y = peso_total_documentos, group = bancada, fill = bancada)) + 
    geom_chicklet(width = 0.75) +
     theme_ipsum_rc(grid=FALSE) +
     theme(legend.position = "bottom") +
     labs(
      x = NULL, y = "Quantidade de documentos", fill = NULL,
      title = paste0("Atuação das Bancadas por Tema"),
      caption = ""
     ) + 
     scale_fill_manual(
     name = NULL,
     values = c(
      "Governo" = "#436f82",
      "Oposição" = "#ae4544"
     )) +
     coord_flip()
  p <- p + theme_ipsum_rc(grid=FALSE)
  p <- p + theme(axis.text.x = element_text(angle = 0, vjust = 0.5)) +theme(axis.text.x = element_text(color = "gray60", size = 10)) +
    theme(legend.position = "top")
  p
  
  qtd_tema <-
    atuacao_temas %>% 
    group_by(tema) %>% 
    summarise(total = sum(peso_total_documentos)) 
  
  tema_destaque <-
    qtd_tema %>%
    arrange(total) %>%
    tail(1) %>%
    purrr::pluck("tema")
  
  descricao_plot_atores <- get_texto_atores_plot_bancadas_por_temas(qtd_tema, atuacao_temas, atores, tema_destaque)
  
  plot(p)
  cat(descricao_plot_atores)
  # cat("\nAo clicar no tema ", tema_destaque, ", temos as seguintes proposições tiveram destaque")

  return(NULL)
}

get_texto_atores_plot_bancadas_por_proposicao <- function(qtd_atuacao, atuacao_bancadas, prop_destaque) {
   total_prop_destaque <- qtd_atuacao %>% filter(nome_formal == prop_destaque) %>% purrr::pluck("total")
  atuacao_prop_destaque <- atuacao_bancadas %>% filter(nome_formal == prop_destaque)
  num_docs_governo <- atuacao_prop_destaque %>% filter(bancada == "Governo") %>% purrr::pluck("peso_total_documentos")
  num_docs_oposicao <- atuacao_prop_destaque %>% filter(bancada == "Oposição") %>% purrr::pluck("peso_total_documentos")
  
  return (paste0("A ", prop_destaque, " teve maior número de atuações, com apresentação de ", total_prop_destaque, " documentos, sendo ", num_docs_governo, " apresentados pelo governo e ",num_docs_oposicao, " pela oposição."))
}

build_atores_plot_bancadas_por_proposicao_tema <- function(atuacao_bancadas, tema) {
  p <- atuacao_bancadas %>% 
    ggplot(aes(x = reorder(nome_formal, peso_total_documentos), y = peso_total_documentos, group = bancada, fill = bancada)) + 
    geom_chicklet(width = 0.75) +
     theme_ipsum_rc(grid=FALSE) +
     theme(legend.position = "bottom") +
     labs(
      x = NULL, y = "Quantidade de documentos", fill = NULL,
      title = "Atuação das bancadas por proposição",
      subtitle = tema,
      caption = ""
     ) +
     scale_fill_manual(
     name = NULL,
     values = c(
      "Governo" = "#436f82",
      "Oposição" = "#ae4544"
     )) +
     coord_flip()
  p <- p + theme_ipsum_rc(grid=FALSE)
  p <- p + theme(axis.text.x = element_text(angle = 0, vjust = 0.5)) +theme(axis.text.x = element_text(color = "gray60", size = 10)) +
    theme(legend.position = "top")
  
  qtd_atuacao <-
    atuacao_bancadas %>% 
    group_by(id_leggo, nome_formal, nome_formal_completo) %>% 
    summarise(total = sum(peso_total_documentos)) 
  
  props_destaque <-
    qtd_atuacao %>% 
    arrange(total) %>% 
    filter(total >= 1) %>% 
    ungroup()
  
  prop_destaque <-
    qtd_atuacao %>% 
    arrange(total) %>% 
    tail(1) %>% 
    purrr::pluck("nome_formal")
  
  descricao_plot_atores <- get_texto_atores_plot_bancadas_por_proposicao(qtd_atuacao, atuacao_bancadas, prop_destaque)
  
  plot(p)
  cat(descricao_plot_atores)
  
  return(list(props_destaque = props_destaque, prop_destaque = prop_destaque))
}

build_atores_plot_por_proposicao <- function(atores_prop_destaque) {
  cat(paste0("\nAbaixo, temos mais detalhes sobre os atores e os respectivos documentos apresentados."))
  atores_pls_bancada <- 
    atores_prop_destaque %>% 
    ungroup() %>% 
    mutate(nome_completo = if_else(bancada == "Oposição", paste("* ", nome_completo), nome_completo))
  
  atores_pls_order <- atores_pls_bancada %>% 
    group_by(nome_completo) %>% 
    summarise(total_docs = sum(peso_total_documentos)) %>% 
    arrange(-total_docs)
  
  atores_pls_plot <- atores_pls_bancada %>% 
    inner_join(atores_pls_order, by="nome_completo")
  
  p <- atores_pls_plot %>% 
    ggplot(aes(x = reorder(nome_completo, total_docs), y = peso_total_documentos, group = tipo_generico, fill = tipo_generico)) + 
      geom_chicklet(width = 0.8) +
       theme(legend.position = "bottom") +
       labs(
        x = NULL, y = "Quantidade de documentos", fill = NULL,
        title = "Atuação por proposição",
        subtitle = atores_pls_plot$nome_formal_completo,
        caption = ""
       ) +
       scale_fill_manual(
       name = NULL,
       values = c(
          'Emenda' =  '#8BD08D',
          'Parecer'= '#69DBC4',
          'Voto em Separado' ='#F6AE2D',
          'Requerimento' = '#8E5B64',
          'Proposição Apensada' ='#2E3532',
          'Outros' = '#CCCCCC'
       )) +
       coord_flip() +
       theme(aspect.ratio = 0.5)+ 
    theme_ipsum_rc(grid=FALSE) +
    theme(axis.text.x = element_text(angle = 0, vjust = 0.5)) + 
    theme(axis.text.x = element_text(color = "gray60", size = 10)) +
    theme(legend.position = "top")
  
  id_leggo <- 
    atores_prop_destaque %>% 
    head(1) %>% 
    purrr::pluck("id_leggo")
  
  link_para_leggo <- paste("https://leggo.org.br/#/proposicao/", id_leggo)
    
  plot(p)
  cat(paste0("Para mais informações sobre a proposição, como o progresso, a rede de influência e uma análise sobre as emendas, [clique aqui](", link_para_leggo, ")."))
}
```

## Pressão e Temperatura
#### Evolução da Pressão e Temperatura ao longo das semanas

```{r, fig.height=7, fig.width=10, results='asis'}
pls_destaque <- pls %>%
  filter(id_leggo %in% temp_pressao_periodo$id_leggo) %>% 
  group_by(id_leggo) %>% 
  arrange(data_apresentacao) %>% 
  slice(n())

if (nrow(pls_destaque) == 0) {
  cat("Nesta semana não houve alterações significativas nas proposições acompanhadas pelo Leg.go.")
}else {
  res <- temp_pressao_periodo %>% 
   left_join(pls_destaque %>% select(id_leggo, nome_formal, apelido), by = "id_leggo") %>% 
    group_by(id_leggo) %>%
    group_map(~ build_temp_pressao_plot(., paste(.$nome_formal, .$apelido,sep=" - "), data_inicio, data_fim, eventos), keep = TRUE)
}
```

## Atores
#### Documentos autorados pelos parlamentares \nna última semana

```{r atores_prop_destaque, fig.height=6, fig.width=10, results='asis'}
if (nrow(atores) == 0) {
  cat("Nesta semana não houve mais de 5 documentos apresentados nas proposições acompanhadas pelo Leg.go.")
}else {
  #Base de dados de Atuação e filtros por data
  atuacao_bancadas_por_tema <- atores %>% 
    dplyr::group_by(bancada, tema) %>% 
    dplyr::summarise(peso_total_documentos = sum(peso_total_documentos))
  
  atuacao_bancadas_por_pl_tema <- atores %>% 
    dplyr::group_by(tema, id_leggo, casa, bancada, nome_formal, nome_formal_completo, sigla_tipo) %>% 
    dplyr::summarise(peso_total_documentos = sum(peso_total_documentos))
  
  build_atores_plot_bancadas_por_temas(atuacao_bancadas_por_tema)
  
  props_list <- atuacao_bancadas_por_pl_tema %>% 
    group_by(tema, id_leggo) %>% 
    group_map(~ build_atores_plot_bancadas_por_proposicao_tema(., .$tema), keep = TRUE)
  props_destaque <- props_list$props_destaque
  prop_destaque <- props_list$prop_destaque

  cat(prop_destaque)
  res <- atores %>% 
  group_by(id_leggo) %>%
    group_map(~ build_atores_plot_por_proposicao(.), keep = T)
}
```