---
title: "PL 490/2007"
output: html_document
---

[Link oficial](http://www.camara.gov.br/proposicoesWeb/fichadetramitacao?idProposicao=345311)

## Resumo da tramitação

A proposta de lei 490 de 2007 foi criada há mais de 11 anos pelo Deputado Homero Pereira do partido PR-MT, que tinha como profissão Produtor Rural e Técnico em Agropecuária, em regime de tramitação Ordinária e atualmente está passando pelas comissões da sua Casa Iniciadora (Câmara dos Deputados). O encaminhamento da proposta de lei foi inicialmente previsto para passar pelas seguintes comissões: CDHM e CCJC. Mas, com o deferimento de um requerimento de redistribuição, a proposta foi encaminhada também à CAPADR, passando a ter a seguinte ordem de comissões: CAPADR,CDHM e CCJC. Na primeira comissão, foi aprovada com apensados em 8 meses após substitutivo. O relator era o Dep. Waldir Neves (PSDB-MS). De volta à CDHM, foi rejeitada em 1 mês, sob relatoria da Dep. Iriny Lopes (PT-ES). Há nove anos, encontra-se na terceira comissão (CCJC) esperando a votação do parecer do relator, Deputado Jerônimo Goergen (PP-RS), após arquivamento, desarquivamento e apensamentos.

```{r, echo=FALSE, message=FALSE, fig.width=10, fig.height=10}
library(vistime)
library(dplyr)

pl_490_2007_data_estado <- frame_data(
  ~ event, ~ group, ~ start, ~ end, ~ color,
  'Sob Análise', 'Estado', '2007-03-20', '2011-01-30','#57d39b',
  'Arquivado', 'Estado', '2011-01-31', '2011-02-15','#f37340',
  'Sob Análise', 'Estado', '2011-02-16', '2015-01-30','#57d39b',
  'Arquivado', 'Estado', '2015-01-31', '2015-02-09','#f37340',
  'Sob Análise', 'Estado', '2015-02-10', '2018-06-12','#57d39b')

pl_490_2007_data_global <- frame_data(
  ~ event, ~ group, ~ start, ~ end, ~ color,
  'Tramitação - Casa de Origem', 'Global', '2007-03-20', '2018-06-12','#87c465')

pl_490_2007_data_casa_origem <- frame_data(
  ~ event, ~ group, ~ start, ~ end, ~ color,
  'Apresentação', 'Casa', '2007-03-20', '2007-03-28','#d6952a',
  'Comissões', 'Casa', '2007-03-29', '2011-01-30','#938ecc',
  'Comissões', 'Casa', '2011-02-16', '2015-01-30','#938ecc',
  'Comissões', 'Casa', '2015-02-10', '2018-06-12','#938ecc')

pl_490_2007_data_comissoes <- frame_data(
  ~ event, ~ group, ~ start, ~ end, ~ color,
  'CDHM', 'Comissões', '2007-03-29', '2007-11-12','#f37340',
  'CAPADR', 'Comissões', '2007-11-19', '2008-07-02','#b1b03a',
  'CDHM', 'Comissões', '2008-07-07', '2009-08-05','#f37340',
  'CCJC', 'Comissões', '2009-08-07', '2018-06-12','#d6952a')

pl_490_2007_data_comissao <- frame_data(
  ~ event, ~ group, ~ start, ~ end, ~ color,
  'Receb.', 'Comissão', '2007-03-29', '2007-04-10','#e08c2d',
  'Análise do Relator', 'Comissão', '2007-04-11', '2007-10-23','#7ac974',
  'Discussão e Votação', 'Comissão', '2007-10-24', '2007-11-12','#a561a2',
  'Receb.', 'Comissão', '2007-11-19', '2007-11-27','#e08c2d',
  'Análise do Relator', 'Comissão', '2007-11-28', '2008-05-27','#7ac974',
  'Discussão e Votação', 'Comissão', '2008-05-28', '2008-07-02','#a561a2',
  'Receb.', 'Comissão', '2008-07-07', '2008-08-03','#e08c2d',
  'Análise do Relator', 'Comissão', '2008-08-04', '2009-06-23','#7ac974',
  'Discussão e Votação', 'Comissão', '2009-06-24', '2009-08-05','#a561a2',
  'Receb.', 'Comissão', '2009-08-07', '2010-03-03','#e08c2d',
  'Análise do Relator', 'Comissão', '2010-03-04', '2011-01-31','#7ac974',
  'Receb.', 'Comissão', '2011-02-10', '2013-05-13','#e08c2d',
  'Análise do Relator', 'Comissão', '2013-05-14', '2015-01-31','#7ac974',
  'Receb.', 'Comissão', '2015-02-10', '2018-01-31','#e08c2d',
  'Análise do Relator', 'Comissão', '2018-02-01', '2018-05-21','#7ac974',
  'Discussão e Votação', 'Comissão', '2018-05-22', '2018-06-12','#a561a2')

pl_490_2007_data_eventos <- frame_data(
  ~ event, ~ group, ~ start, ~ end, ~ color,
  'Distribuição às comissões', 'Evento', '2007-03-28', '2007-03-28','#f9929f',
  'Designação do relator', 'Evento', '2007-04-11', '2007-04-11','#87c465',
  'Início do Prazo para Emendas', 'Evento', '2007-04-16', '2007-04-16','#87c465',
  'Fim do Prazo para Emendas', 'Evento', '2007-04-24', '2007-04-24','#87c465',
  'Parecer', 'Evento', '2007-08-27', '2007-08-27','#a561a2',
  'Parecer', 'Evento', '2007-10-19', '2007-10-19','#a561a2',
  'Pedido de vista', 'Evento', '2007-10-24', '2007-10-24','#b1b03a',
  'Despacho de Redistribuição', 'Evento', '2007-11-06', '2007-11-06','#f9929f',
  'Designação do relator', 'Evento', '2007-11-28', '2007-11-28','#87c465',
  'Início do Prazo para Emendas', 'Evento', '2007-11-30', '2007-11-30','#87c465',
  'Fim do Prazo para Emendas', 'Evento', '2007-12-12', '2007-12-12','#87c465',
  'Parecer', 'Evento', '2008-03-27', '2008-03-27','#a561a2',
  'Início do Prazo para Emendas ao Subst.', 'Evento', '2008-04-01', '2008-04-01','#87c465',
  'Fim do Prazo para Emendas ao Subst.', 'Evento', '2008-04-09', '2008-04-09','#87c465',
  'Parecer', 'Evento', '2008-05-13', '2008-05-13','#a561a2',
  'Pedido de vista', 'Evento', '2008-05-28', '2008-05-28','#b1b03a',
  'Voto em separado', 'Evento', '2008-06-10', '2008-06-10','#7590ab',
  'Aprovado parecer', 'Evento', '2008-07-02', '2008-07-02','#1bded1',
  'Designado relator', 'Evento', '2008-08-04', '2008-08-04','#87c465',
  'Parecer', 'Evento', '2009-06-22', '2009-06-22','#a561a2',
  'Aprovado Req. Aud. Pub.', 'Evento', '2009-07-08', '2009-07-08','#a561a2',
  'Aprovado parecer', 'Evento', '2009-08-05', '2009-08-05','#1bded1',
  'Designação do relator', 'Evento', '2010-03-04', '2010-03-04','#87c465',
  'Arquivado', 'Evento', '2011-01-31', '2011-01-31','#87c465',
  'Desarquivado', 'Evento', '2011-02-16', '2011-02-16','#87c465',
  'Designação do relator', 'Evento', '2013-05-14', '2013-05-14','#87c465',
  'Arquivado', 'Evento', '2015-01-31', '2015-01-31','#87c465',
  'Desarquivado', 'Evento', '2015-02-10', '2015-02-10','#87c465',
  'Designação do relator', 'Evento', '2018-02-01', '2018-02-01','#87c465',
  'Parecer', 'Evento', '2018-04-10', '2018-04-10','#a561a2',
  'Voto em separado', 'Evento', '2018-05-22', '2018-05-22','#7590ab',
  'Retirado de pauta', 'Evento', '2018-06-12', '2018-06-12','#bd0624')

pl_490_2007_data_general <- bind_rows(
  pl_490_2007_data_estado,
  pl_490_2007_data_global,
  pl_490_2007_data_casa_origem,
  pl_490_2007_data_comissoes,
  pl_490_2007_data_comissao,
  pl_490_2007_data_eventos)

vistime(pl_490_2007_data_general)
```
