COMISSOES_CAMARA <- data.frame("comissao" = c("Comissão de Agricultura, Pecuária, Abastecimento e Desenvolvimento Rural",
                                              "Comissão de Ciência e Tecnologia, Comunicação e Informática",
                                              "Comissão de Constituição e Justiça e de Cidadania",
                                              "Comissão de Cultura",
                                              "Comissão de Defesa do Consumidor",
                                              "Comissão de Defesa dos Direitos da Mulher",
                                              "Comissão de Defesa dos Direitos da Pessoa Idosa",
                                              "Comissão de Defesa dos Direitos das Pessoas com Deficiência",
                                              "Comissão de Desenvolvimento Urbano",
                                              "Comissão de Desenvolvimento Econômico, Indústria, Comércio e Serviços",
                                              "Comissão de Direitos Humanos e Minorias",
                                              "Comissão de Educação",
                                              "Comissão do Esporte",
                                              "Comissão de Finanças e Tributação",
                                              "Comissão de Fiscalização Financeira e Controle",
                                              "Comissão de Integração Nacional, Desenvolvimento Regional e da Amazônia",
                                              "Comissão de Legislação Participativa",
                                              "Comissão de Meio Ambiente e Desenvolvimento Sustentável",
                                              "Comissão de Minas e Energia",
                                              "Comissão de Relações Exteriores e de Defesa Nacional",
                                              "Comissão de Segurança Pública e Combate ao Crime Organizado",
                                              "Comissão de Seguridade Social e Família",
                                              "Comissão de Trabalho, de Administração e Serviço Público",
                                              "Comissão de Turismo",
                                              "Comissão de Viação e Transportes"),
                               "regex"=c(c("comiss.o de agricultura, pecu.ria, abastecimento e desenvolvimento rural", "capadr"),
                                         c("comiss.o de ci.ncia e tecnologia, comunica..o e informatica", "cctci"),
                                         c("comiss.o de constitui..o e justi.a e de cidadania", "ccjc"),
                                         c("comiss.o de cultura", "ccult"),
                                         c("comiss.o de defesa do consumidor", "cdc"),
                                         c("comiss.o de defesa dos direitos da mulher", "cmulher"),
                                         c("comiss.o de defesa dos direitos da pessoa idosa", "cidoso"),
                                         c("comiss.o de defesa dos direitos das pessoas com defici.ncia", "cpd"),
                                         c("comiss.o de desenvolvimento urbano", "cdu"),
                                         c("comiss.o de desenvolvimento econ.mico, ind.stria, com.rcio e servi.os", "cdeics"),
                                         c("comiss.o de direitos humanos e minorias", "cdhm"),
                                         c("comiss.o de educa..o", "ce"),
                                         c("comiss.o do esporte", "cespo"),
                                         c("comiss.o de finan.as e tributa..o", "cft"),
                                         c("comiss.o de fiscaliza..o financeira e controle", "cffc"),
                                         c("comiss.o de integra..o nacional, desenvolvimento regional e da amaz.nia", "cindra"),
                                         c("comiss.o de legisla..o participativa", "clp"),
                                         c("comiss.o de meio ambiente e desenvolvimento sustent.vel", "cmads"),
                                         c("comiss.o de minas e energia", "cme"),
                                         c("comiss.o de rela..es exteriores e de defesa nacional", "credn"),
                                         c("comiss.o de seguran.a p.blica e combate ao crime organizado", "cspcco"),
                                         c("comiss.o de seguridade social e fam.lia", "cssf"),
                                         c("comiss.o de trabalho, de administra..o e servi.o p.blico", "ctasp"),
                                         c("comiss.o de turismo", "ctur"),
                                         c("comiss.o de via..o e transportes", "cvt")))
                               
                               