---
output: html_notebook
params:
  lei: "lei"
  senado_id: 127753
---
```{r imports, echo=FALSE, message=FALSE}
library(tidyverse)

source(here::here('code/vis/tramitacao/extract-informations.R'))

data <- extract_informations_from_single_house(345311, 'camara', 'https://analytics-ufcg.github.io/agora-digital/reports/report_345311_camara.html')
```
# Projeto de Lei `r toString(data$nome)`

### Informações Gerais

```{r, echo=FALSE, message=FALSE}
bill_id_cadastro_positivo_camara <- 2160860
bill_id_cadastro_positivo_senado <- 129808
bill_id_pl_veneno_camara <- 46249
bill_id_pl_veneno_senado <- 41703
bill_id_teto_remunatorio_camara <- 2121442
bill_id_teto_remunatorio_senado <- 127753

```
#### Autor:
 `r toString(data$autor)`
 
#### Casa de Origem:
 `r toString(data$casa_origem)`

#### Data de Apresentação:
 `r toString(data$data_apresentacao)`

#### Ementa:
`r toString(data$ementa)`

#### Status Atual:
`r toString(data$status_atual)`

#### Último Relator:
`r toString(data$ultimo_relator)`

#### Tramitação no Senado
```{r}
# TODO
```
#### Tabelas de apensação
```{r echo=FALSE, message=FALSE}

table_apensadas_camara <- gera_tabela_apensadas_camara(46249) 
table_apensadas_senado <- gera_tabela_apensadas_senado(127753) 
knitr::kable(table_apensadas_camara, caption = "Lista de Leis Apensadas Câmara")
knitr::kable(table_apensadas_senado, caption = "Lista de Leis Apensadas Senado")

# table_apensadas <- gera_tabela_apensadas_senado(bill_id_pl_veneno_senado)
# knitr::kable(table_apensadas, caption = "Lista de Leis Apensadas")

```


