---
title: "Dados gerados pelo Analyzer na Camara"
output: html_notebook
---

O `analyzer.R` realiza operações de reconhecimento e extração dos eventos e as fases nos dataframes das tramitação das proposições na Câmara dos Deputados e no Senado Federal. Como possuem APIs distintas, cada casa possui um analyzer próprio adequado para os dados disponíveis em suas respectivas APIs. 

O `camara-analyzer.R` extrai os locais (Comissões e Plenário), as fases da proposição na casa e eventos que ocorreram durante a tramitação de uma proposição na Câmara.

```{r message=FALSE}
source(here::here("R/analyzers/analyzer.R"))
library(magrittr)
library(tidyverse)
id_pl_veneno_camara <- 46249
process_proposicao(id_pl_veneno_camara, 'camara')
```

Os dados retornados pela função **process_proposicao(id, "camara")**, além dos retornados pela [API Dados Abertos da Câmara](https://dadosabertos.camara.leg.br/swagger/api.html), estão distribuídos nas seguintes colunas:

* `evento`: Eventos importantes que ocorreram na tramitação;
* `local`: Local onde a proposição esteve/está;
* `casa`: A fase correspondente à situação da proposição na **Casa** onde ela se encontra. Podem ser: 
    * Apresentação: quando é apresentada na Câmara de Deputados;
    * Comissões: quando é designada às comissões para que um Relator seja designado, apresente seu Parecer e ele seja votado;
    * Plenário: quando é encaminhada ao Plenário (isso ocorre quando há divergência entre os Pareceres aprovados dos Relatores nas Comissões).
* `situacao_comissao`: Situação da proposição na **Comisssão** onde ela se encontra. Podem ser:
    * recebimento: quando a proposição é recebida na Comissão;
    * analise_do_relator: quando o Relator é designado;
    * discussao_votacao: quando o Relator apresenta seu Parecer e ele passa a ser votado na Comissão;
    * encaminhamento: quando a proposição é votada e é encaminhada para a próxima Comissão, Plenário ou Casa.



