---
title: "Relatório do Projeto de Lei do Senado 449"
output: html_notebook
---

```{r, echo = FALSE}
library(tidyverse)
library(here)
library(jsonlite)
library(vistime)
source(here("code/senado-lib.R"))
```

```{r, echo = FALSE}
bill_id <- 127753
bill_data <- fetch_proposicao(bill_id, 'senado')
```

Apelido da proposição:
```{r, echo = FALSE}
bill_data$apelido_materia
```

Autor da proposição:
```{r, echo = FALSE}
bill_data$nome_autor
```

Data de apresentação:
```{r, echo = FALSE}
bill_data$data_apresentacao
```

Casa de origem:
```{r, echo = FALSE}
bill_data$nome_casa_origem
```

Assunto geral:
```{r, echo = FALSE}
bill_data$assunto_geral
```

Assunto específico:
```{r, echo = FALSE}
bill_data$assunto_especifico
```

Ementa:
```{r, echo = FALSE}
bill_data$ementa_materia
```

Tabela de frequência de eventos importantes:
```{r, echo = FALSE, message = FALSE, warning = FALSE}
setwd('../data/Senado/')
bill_passage_visualization <- read_csv(paste0(bill_id,"-bill-passage-visualization-senado.csv"))
bill_passage_visualization %>% select(evento) %>% group_by(evento) %>%
  filter(!is.na(evento)) %>% summarise(frequência = n()) %>%
  arrange(-frequência)
```

Gráfico da Visualização dos locais, eventos e fases de uma proposição no Senado, nele podemos ver quais são as sub-fases por local 
```{r, echo = FALSE, message = FALSE, warning = FALSE}
setwd('../data/vis/tramitacao/')
read_csv(paste0(bill_id,"-data-senado.csv")) %>%
vistime(events="label", groups="group", title="Fases da tramitação", showLabels=FALSE)
```