---
title: "Passado distante dos progressos"
author: "Matheus Leal"
date: Sys.Date()
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(plotly)
```

```{r}
progressos <- readr::read_csv('../data/distancias/progressos.csv')
temas <- readr::read_csv('../data/tabela_geral_ids_casa.csv') %>% 
  mutate(id_ext = ifelse(is.na(id_camara), id_senado, id_camara))
progresso_temas <- merge(progressos, temas, by.x = "id_ext", by.y = "id_ext")
```

```{r}
progresso_temas <- progresso_temas %>% 
                   mutate(fase_local = ifelse(is.na(local), fase_global, paste(fase_global, local, sep=" - ")))
data_subset <- progresso_temas[ , c("id_ext", "data_inicio", "data_fim", "tema", "apelido", "fase_local")]
```

```{r}
hoje <-Sys.Date()
progresso_data <- data_subset %>% 
                  rowwise() %>% 
                  filter(is.na(data_fim)) %>% select(-data_fim) %>% 
                  mutate(semanas_decorridas = lubridate::time_length(
                                              lubridate::interval(
                                              lubridate::ymd(unlist(strsplit(as.character(data_inicio), " "))[1]), 
                                              lubridate::ymd(hoje)), "week")) %>%
                  filter(!is.na(data_inicio)) %>% 
                  tidyr::separate_rows(tema,sep=';')

```

```{r}
mediana_por_tema <- progresso_data %>% 
                    group_by(tema) %>% 
                    summarise(mediana = median(semanas_decorridas))

p <-ggplot2::ggplot(data=mediana_por_tema, ggplot2::aes(x=tema, y=mediana, color=tema)) +
    ggplot2::geom_bar(stat="identity", fill="white")  +
    ggplot2::labs(x="Tema", y="Mediana das semanas decorridas") +
    ggplot2::theme(axis.text.x = element_text(angle = 90, hjust = 1))

p
```
```{r}
agenda_nacional <- progresso_data %>% filter(tema=="Agenda Nacional")


```

