---
title: "Apensadas"
output: html_notebook
---


```{r, echo = FALSE}
library(tidyverse)
source(here::here("code/senado-lib.R"))
source(here::here("code/camara-lib.R"))
```

```{r, echo = FALSE}
bill_id_camara <- 46249
bill_id_senado <- 71687
```

```{r, echo = FALSE}
gera_tabela_apensadas <- function(bill_id_camara, bill_id_senado) {
  url_senado <- "https://www25.senado.leg.br/web/atividade/materias/-/materia/"
  url_camara <- "http://www.camara.gov.br/proposicoesWeb/fichadetramitacao?idProposicao="
  
  camara <- 
    fetch_apensadas(bill_id_camara) %>%
    mutate(casa = "Câmara", apensadas = paste0("[", apensadas, "](", paste0(url_camara, apensadas), ")"))
  
  senado <- 
    fetch_bill(bill_id_senado)  %>% 
    mutate(proposicoes_apensadas = strsplit(.$proposicoes_apensadas, " ")) %>%
    unnest() %>%
    select(apensadas = proposicoes_apensadas)
  
  senado <-
    senado %>%
    mutate(casa = "Senado", apensadas = paste0("[", apensadas, "](", paste0(url_senado, apensadas), ")"))
  
  rbind(camara, senado)
}
```


```{r, echo = FALSE, results='asis'}
knitr::kable(gera_tabela_apensadas(bill_id_camara, bill_id_senado), caption = "Proposições")
```

