---
title: "Visualização das proposições"
output: html_notebook
---


```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(rcongresso)
source(here::here("code/vis/tramitacao/extract-informations.R"))
```

```{r, echo = FALSE, message=FALSE, warning=FALSE}
bill_id_cadastro_positivo_camara <- 2160860
bill_id_cadastro_positivo_senado <- 129808
bill_id_pl_veneno_camara <- 46249
bill_id_pl_veneno_senado <- 41703
bill_id_teto_remunatorio_camara <- 2121442
bill_id_teto_remunatorio_senado <- 127753
url <- "https://analytics-ufcg.github.io/agora-digital/reports/teto_remuneratorio-camara.html"

ids_df <-
    frame_data(~ id_camara, ~ id_senado, ~ url,
             bill_id_cadastro_positivo_camara, bill_id_cadastro_positivo_senado, url,
             bill_id_pl_veneno_camara, bill_id_pl_veneno_senado, url,
             bill_id_teto_remunatorio_camara, bill_id_teto_remunatorio_senado, url)

ids_df_single_house <-
  frame_data(~ id, ~ casa, ~ url,
             132865, "senado", "https://analytics-ufcg.github.io/agora-digital/reports/report_132865_senado.html",
             257161, "camara", "https://analytics-ufcg.github.io/agora-digital/reports/report_257161_camara.html",
             345311, "camara", "https://analytics-ufcg.github.io/agora-digital/reports/report_345311_camara.html",
             2056568, "camara", "https://analytics-ufcg.github.io/agora-digital/reports/report_2056568_camara.html",
             2120775, "camara", "https://analytics-ufcg.github.io/agora-digital/reports/report_2120775_camara.html")
```

```{r, echo = FALSE, message = FALSE, warning=FALSE}
a <- gera_tabela_proposicoes_congresso(ids_df)
b <- gera_tabela_proposicoes_uma_casa(ids_df_single_house)
```

```{r, echo = FALSE, message = FALSE, results='asis'}
#knitr::kable(a, caption = "Proposições")
knitr::kable(b, caption = "Proposições")
```
