---
output: html_document
params:
  senado_id: 132865
  camara_id: 2088990
---
```{r imports, echo=FALSE, message=FALSE, error=FALSE, warning=FALSE, timeout= 4000000}
source(here::here('R/data-formatter-ficha.R'))
source(here::here('view/visualizer/build-chart.R'))

data <- extract_informations_all_houses(params$senado_id, params$camara_id)
chart <- create_chart_camara_senado(params$senado_id, params$camara_id)
emendas <- gera_tabela_emendas_senado(params$senado_id)
```
# Projeto de Lei `r toString(paste0(data$nome))`

### Informações Gerais

#### Autor:
 `r toString(data$autor)`

#### Casa de Origem:
 `r toString(data$casa_origem)`

#### Data de Apresentação:
 `r toString(data$data_apresentacao)`

#### Ementa:
`r toString(data$ementa)`

#### Status Atual:
`r toString(data$status_atual)`

#### Último Relator:
`r toString(data$ultimo_relator)`

#### Tramitação 
```{r echo=FALSE, message=FALSE}
chart
```

#### Tabelas de emendas

```{r echo=FALSE, message=FALSE, error=FALSE, warning=FALSE}
knitr::kable(emendas)
```

