---
title: "Relatório - Histórico do progresso por tema"
date: "`r Sys.Date()`"
author: "Matheus Leal"
output:  
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---

```{r setup, include=FALSE}
library(rmdformats)
library(tidyverse)
library(plotly)
library(lubridate)
progressos <- read_csv('../../data/distancias/progressos.csv')
temas <- read_csv('../../data/tabela_geral_ids_casa.csv') %>% 
  mutate(id_ext = ifelse(is.na(id_camara), id_senado, id_camara))
```

```{r}


data <- merge(progressos, temas, by.x = "id_ext", by.y = "id_ext")
data_subset <- data[ , c("id_ext", "data_inicio")]  
data_by_column <- data[complete.cases(data_subset), ] %>% 
                  mutate(fase_local = ifelse(is.na(local), 
                                             fase_global, 
                                             paste(fase_global, local, sep=" - ")))

agenda_nacional <- data_by_column[is.na(data_by_column$data_fim), ]  %>% 
              filter(tema == "Agenda Nacional") %>% 
              group_by(fase_local) %>% 
              summarise(pls = n())
meio_ambiente <- data_by_column[is.na(data_by_column$data_fim), ]  %>% 
              filter(tema == "Meio Ambiente") %>% 
              group_by(fase_local) %>% 
              summarise(pls = n())
geral <- data_by_column[is.na(data_by_column$data_fim), ]  %>% 
              group_by(fase_local) %>% 
              summarise(pls = n())
```


```{r}
p0 <- plot_ly(
    type = 'scatterpolar',
    fill = 'toself'
  ) %>%
  add_trace(
    r = geral$pls,
    theta = geral$fase_local,
    name = 'Geral'
  )  %>% 
  layout(
    polar = list(
      radialaxis = list(
        visible = T,
        range = c(0,35)
      )
    ),
    showlegend = F
  )

p <- plot_ly(
    type = 'scatterpolar',
    fill = 'toself'
  ) %>%
  add_trace(
    r = agenda_nacional$pls,
    theta = agenda_nacional$fase_local,
    name = 'Agenda Nacional'
  )  %>% 
  layout(
    polar = list(
      radialaxis = list(
        visible = T,
        range = c(0,15)
      )
    ),
    showlegend = F
  )

p2 <- plotly::plot_ly(
    type = 'scatterpolar',
    fill = 'toself'
  ) %>%
  plotly::add_trace(
    r = meio_ambiente$pls,
    theta = meio_ambiente$fase_local,
    name = 'Agenda Nacional'
  )  %>% 
  plotly::layout(
    polar = list(
      radialaxis = list(
        visible = T,
        range = c(0,15)
      )
    ),
    showlegend = F
  )

plotly::ggplotly(p0)
plotly::ggplotly(p)
plotly::ggplotly(p2)
```

```{r}
hoje <-Sys.Date()
data_subset <- data[ , c("id_ext", "data_inicio", "data_fim", "tema")] 
progresso_data <- data_subset %>% 
  rowwise() %>% 
  filter(is.na(data_fim)) %>% 
  mutate(semanas = lubridate::time_length(lubridate::interval(
                                          lubridate::ymd(
                                          unlist(
                                          strsplit(as.character(data_inicio), " "))[1]), 
                                          lubridate::ymd(hoje)), "week")) %>% 
  filter(!is.na(data_inicio))

mediana_por_tema <- progresso_data %>% 
                    group_by(tema) %>% 
                    summarise(mediana = median(semanas))

p <- ggplot2::diamonds %>% 
  plot_ly(
  x = ~mediana_por_tema$tema, 
  y = ~mediana_por_tema$mediana)

ggplotly(p)
```
```{r}
summary(progresso_data$semanas)
boxplot(progresso_data$semanas)
```
```{r}
data_subset <- data[ , c("id_ext", "data_inicio", "data_fim", "tema", "fase_global", "apelido")]
data_by_column <- data[complete.cases(data_subset), ] %>% 
                  mutate(fase_local = ifelse(is.na(local), 
                                             fase_global, 
                                             paste(fase_global, 
                                                   local, 
                                                   sep=" - ")))
progresso_data2 <- data_subset %>% 
  rowwise() %>% 
  mutate(semanas = lubridate::time_length(
                   lubridate::interval(
                   lubridate::ymd(unlist(strsplit(as.character(data_inicio), " "))[1]), 
                   lubridate::ymd(hoje)), "week")) %>%           
  filter(!is.na(data_inicio))

p <- progresso_data2 %>%
  plotly::plot_ly(
    x = ~fase_global, 
    y = ~apelido, 
    color = ~tema, 
    frame = ~semanas, 
    text = ~as.character(apelido), 
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers'
  )
plotly::ggplotly(p)
```

