---
title: "Histórico dos progressos com local"
author: "Matheus Leal"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---

```{r knitr_init, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, paged.print=FALSE, results="asis"}
library(tidyverse)
library(lubridate)
library(knitr)
library(plotly)
opts_chunk$set(echo = TRUE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = FALSE,
               comment = NA,
               message = FALSE,
               warning = FALSE)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
progressos <- readr::read_csv('../../data/distancias/progressos.csv')
temas <- readr::read_csv('../../data/tabela_geral_ids_casa.csv') %>% 
  mutate(id_ext = ifelse(is.na(id_camara), id_senado, id_camara))
progresso_temas <- merge(progressos, temas, by.x = "id_ext", by.y = "id_ext")
tramitacoes <- readr::read_csv('../../data/distancias/trams.csv')

t <- tramitacoes %>%  select(id_ext, sigla_local, local, texto_tramitacao, data) %>% arrange(id_ext, data)
```

```{r}
trams <- tramitacoes %>% 
  filter(is.na(tipo_documento)) %>% 
  select(id_ext, local, data, texto_tramitacao) %>% 
  arrange(id_ext, data) %>% 
  group_by(id_ext,local) %>% 
  summarise(data_inicio = first(data),
            data_fim = last(data))
df <- trams %>% filter(id_ext=="46249") 
#progresso_local <- merge(temas, trams, by.x = "id_ext", by.y = "id_ext")
```

